version: '3.8'
services:
  xyra_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xyra/xyra-app-combined:latest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - INTERNAL_BACKEND_URL=http://localhost:8000
      - API_V1_STR=/api/v1
      - NEXT_PUBLIC_API_BASE_URL=/api/v1
    networks:
      - xyra_network

networks:
  xyra_network:
