name: Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! 📚

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear instructions
        - Typo/grammar error
        - Broken link
        - Missing examples
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        Please provide:
        - File path: e.g., README.md, CONTRIBUTING.md, documentation/getting_started.md
        - Section/heading: e.g., "Installation", "API Reference"
        - Line number (if applicable)
        - URL (if web-based docs)
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: A clear and concise description of what's wrong or missing
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How would you improve this documentation?
      placeholder: Describe what changes would make this better

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here
