"""Add fixed_charge_per_outcome to OutcomeBasedConfig

Revision ID: 1a6ee7631f5f
Revises: 7bce887a9187
Create Date: 2025-07-06 18:44:55.482635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6ee7631f5f'
down_revision: Union[str, None] = '7bce887a9187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcomebasedconfig', sa.Column('fixed_charge_per_outcome', sa.Float(), nullable=True))
    op.alter_column('outcomebasedconfig', 'percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcomebasedconfig', 'percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('outcomebasedconfig', 'fixed_charge_per_outcome')
    # ### end Alembic commands ###
