"""Initial migration

Revision ID: 21ec5b45cc17
Revises: 
Create Date: 2025-05-13 09:06:43.738885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ec5b45cc17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activitybasedconfig_billing_model_id_fkey', 'activitybasedconfig', type_='foreignkey')
    op.create_foreign_key(None, 'activitybasedconfig', 'billingmodel', ['billing_model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('agentactivity_agent_id_fkey', 'agentactivity', type_='foreignkey')
    op.create_foreign_key(None, 'agentactivity', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('agentcost_agent_id_fkey', 'agentcost', type_='foreignkey')
    op.create_foreign_key(None, 'agentcost', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('agentoutcome_agent_id_fkey', 'agentoutcome', type_='foreignkey')
    op.create_foreign_key(None, 'agentoutcome', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.add_column('invoice', sa.Column('stripe_checkout_session_id', sa.String(), nullable=True))
    op.add_column('invoice', sa.Column('stripe_payment_link', sa.String(), nullable=True))
    op.drop_constraint('outcomebasedconfig_billing_model_id_fkey', 'outcomebasedconfig', type_='foreignkey')
    op.create_foreign_key(None, 'outcomebasedconfig', 'billingmodel', ['billing_model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('seatbasedconfig_billing_model_id_fkey', 'seatbasedconfig', type_='foreignkey')
    op.create_foreign_key(None, 'seatbasedconfig', 'billingmodel', ['billing_model_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seatbasedconfig', type_='foreignkey')
    op.create_foreign_key('seatbasedconfig_billing_model_id_fkey', 'seatbasedconfig', 'billingmodel', ['billing_model_id'], ['id'])
    op.drop_constraint(None, 'outcomebasedconfig', type_='foreignkey')
    op.create_foreign_key('outcomebasedconfig_billing_model_id_fkey', 'outcomebasedconfig', 'billingmodel', ['billing_model_id'], ['id'])
    op.drop_column('invoice', 'stripe_payment_link')
    op.drop_column('invoice', 'stripe_checkout_session_id')
    op.drop_constraint(None, 'agentoutcome', type_='foreignkey')
    op.create_foreign_key('agentoutcome_agent_id_fkey', 'agentoutcome', 'agent', ['agent_id'], ['id'])
    op.drop_constraint(None, 'agentcost', type_='foreignkey')
    op.create_foreign_key('agentcost_agent_id_fkey', 'agentcost', 'agent', ['agent_id'], ['id'])
    op.drop_constraint(None, 'agentactivity', type_='foreignkey')
    op.create_foreign_key('agentactivity_agent_id_fkey', 'agentactivity', 'agent', ['agent_id'], ['id'])
    op.drop_constraint(None, 'activitybasedconfig', type_='foreignkey')
    op.create_foreign_key('activitybasedconfig_billing_model_id_fkey', 'activitybasedconfig', 'billingmodel', ['billing_model_id'], ['id'])
    # ### end Alembic commands ###
