"""Add human equivalent cost fields and value receipt models

Revision ID: 2f9630c0d585
Revises: c3957c7e8da8
Create Date: 2025-07-15 17:38:08.773674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9630c0d585'
down_revision: Union[str, None] = 'c3957c7e8da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitybasedconfig', sa.Column('human_cost_per_unit', sa.Float(), nullable=True))
    op.add_column('activitybasedconfig', sa.Column('human_time_per_unit_minutes', sa.Float(), nullable=True))
    op.add_column('activitybasedconfig', sa.Column('human_hourly_rate', sa.Float(), nullable=True))
    op.add_column('activitybasedconfig', sa.Column('human_error_rate', sa.Float(), nullable=True))
    op.add_column('activitybasedconfig', sa.Column('human_quality_score', sa.Float(), nullable=True))
    op.add_column('agentbasedconfig', sa.Column('human_fte_monthly_cost', sa.Float(), nullable=True))
    op.add_column('agentbasedconfig', sa.Column('human_fte_productivity_ratio', sa.Float(), nullable=True))
    op.add_column('agentbasedconfig', sa.Column('human_onboarding_cost', sa.Float(), nullable=True))
    op.add_column('agentbasedconfig', sa.Column('human_overhead_percentage', sa.Float(), nullable=True))
    op.add_column('outcomebasedconfig', sa.Column('human_equivalent_cost_percentage', sa.Float(), nullable=True))
    op.add_column('outcomebasedconfig', sa.Column('human_success_rate', sa.Float(), nullable=True))
    op.add_column('outcomebasedconfig', sa.Column('human_time_to_outcome_days', sa.Float(), nullable=True))
    op.add_column('outcomebasedconfig', sa.Column('human_labor_cost_per_hour', sa.Float(), nullable=True))
    op.add_column('outcomebasedconfig', sa.Column('human_overhead_multiplier', sa.Float(), nullable=True))
    op.add_column('workflowbasedconfig', sa.Column('human_platform_cost_monthly', sa.Float(), nullable=True))
    op.add_column('workflowbasedconfig', sa.Column('human_workflow_overhead_percentage', sa.Float(), nullable=True))
    op.add_column('workflowbasedconfig', sa.Column('human_training_cost_per_workflow', sa.Float(), nullable=True))
    op.add_column('workflowbasedconfig', sa.Column('human_management_hours_per_workflow', sa.Float(), nullable=True))
    op.add_column('workflowtype', sa.Column('human_cost_per_workflow', sa.Float(), nullable=True))
    op.add_column('workflowtype', sa.Column('human_time_per_workflow_hours', sa.Float(), nullable=True))
    op.add_column('workflowtype', sa.Column('human_skill_level_required', sa.String(), nullable=True))
    op.add_column('workflowtype', sa.Column('human_error_rate_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflowtype', 'human_error_rate_percentage')
    op.drop_column('workflowtype', 'human_skill_level_required')
    op.drop_column('workflowtype', 'human_time_per_workflow_hours')
    op.drop_column('workflowtype', 'human_cost_per_workflow')
    op.drop_column('workflowbasedconfig', 'human_management_hours_per_workflow')
    op.drop_column('workflowbasedconfig', 'human_training_cost_per_workflow')
    op.drop_column('workflowbasedconfig', 'human_workflow_overhead_percentage')
    op.drop_column('workflowbasedconfig', 'human_platform_cost_monthly')
    op.drop_column('outcomebasedconfig', 'human_overhead_multiplier')
    op.drop_column('outcomebasedconfig', 'human_labor_cost_per_hour')
    op.drop_column('outcomebasedconfig', 'human_time_to_outcome_days')
    op.drop_column('outcomebasedconfig', 'human_success_rate')
    op.drop_column('outcomebasedconfig', 'human_equivalent_cost_percentage')
    op.drop_column('agentbasedconfig', 'human_overhead_percentage')
    op.drop_column('agentbasedconfig', 'human_onboarding_cost')
    op.drop_column('agentbasedconfig', 'human_fte_productivity_ratio')
    op.drop_column('agentbasedconfig', 'human_fte_monthly_cost')
    op.drop_column('activitybasedconfig', 'human_quality_score')
    op.drop_column('activitybasedconfig', 'human_error_rate')
    op.drop_column('activitybasedconfig', 'human_hourly_rate')
    op.drop_column('activitybasedconfig', 'human_time_per_unit_minutes')
    op.drop_column('activitybasedconfig', 'human_cost_per_unit')
    # ### end Alembic commands ###
