"""remove_config_column_from_billing_model

Revision ID: 5331bdb51fd7
Revises: fe1e8e8782e3
Create Date: 2025-06-03 20:28:57.215764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5331bdb51fd7'
down_revision: Union[str, None] = 'fe1e8e8782e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hybridconfig',
    sa.Column('billing_model_id', sa.Integer(), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_model_id'], ['billingmodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hybridconfig_id'), 'hybridconfig', ['id'], unique=False)
    op.drop_column('billingmodel', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billingmodel', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_hybridconfig_id'), table_name='hybridconfig')
    op.drop_table('hybridconfig')
    # ### end Alembic commands ###
