"""add_workflow_based_billing_models

Revision ID: 6ae166d58868
Revises: 1718f4c8a429
Create Date: 2025-06-21 21:53:39.572528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae166d58868'
down_revision: Union[str, None] = '1718f4c8a429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitmenttier',
    sa.Column('billing_model_id', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('minimum_workflows_per_month', sa.Integer(), nullable=False),
    sa.Column('minimum_monthly_revenue', sa.Float(), nullable=False),
    sa.Column('included_workflows', sa.Integer(), nullable=False),
    sa.Column('included_workflow_types', sa.String(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('platform_fee_discount', sa.Float(), nullable=True),
    sa.Column('commitment_period_months', sa.Integer(), nullable=False),
    sa.Column('overage_rate_multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_model_id'], ['billingmodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitmenttier_id'), 'commitmenttier', ['id'], unique=False)
    op.create_table('workflowbasedconfig',
    sa.Column('billing_model_id', sa.Integer(), nullable=False),
    sa.Column('base_platform_fee', sa.Float(), nullable=False),
    sa.Column('platform_fee_frequency', sa.String(), nullable=False),
    sa.Column('default_billing_frequency', sa.String(), nullable=False),
    sa.Column('volume_discount_enabled', sa.Boolean(), nullable=True),
    sa.Column('volume_discount_threshold', sa.Integer(), nullable=True),
    sa.Column('volume_discount_percentage', sa.Float(), nullable=True),
    sa.Column('overage_multiplier', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_model_id'], ['billingmodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowbasedconfig_id'), 'workflowbasedconfig', ['id'], unique=False)
    op.create_table('workflowtype',
    sa.Column('billing_model_id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_per_workflow', sa.Float(), nullable=False),
    sa.Column('estimated_compute_cost', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('complexity_level', sa.String(), nullable=False),
    sa.Column('expected_roi_multiplier', sa.Float(), nullable=True),
    sa.Column('business_value_category', sa.String(), nullable=True),
    sa.Column('volume_tier_1_threshold', sa.Integer(), nullable=True),
    sa.Column('volume_tier_1_price', sa.Float(), nullable=True),
    sa.Column('volume_tier_2_threshold', sa.Integer(), nullable=True),
    sa.Column('volume_tier_2_price', sa.Float(), nullable=True),
    sa.Column('volume_tier_3_threshold', sa.Integer(), nullable=True),
    sa.Column('volume_tier_3_price', sa.Float(), nullable=True),
    sa.Column('billing_frequency', sa.String(), nullable=True),
    sa.Column('minimum_charge', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_model_id'], ['billingmodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowtype_id'), 'workflowtype', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflowtype_id'), table_name='workflowtype')
    op.drop_table('workflowtype')
    op.drop_index(op.f('ix_workflowbasedconfig_id'), table_name='workflowbasedconfig')
    op.drop_table('workflowbasedconfig')
    op.drop_index(op.f('ix_commitmenttier_id'), table_name='commitmenttier')
    op.drop_table('commitmenttier')
    # ### end Alembic commands ###
