"""restore_human_equivalent_value_fields

Revision ID: 80f41e78541c
Revises: db3353e45f5c
Create Date: 2025-07-23 09:25:58.420965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f41e78541c'
down_revision: Union[str, None] = 'db3353e45f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitybasedconfig', sa.Column('human_equivalent_value', sa.Float(), nullable=True))
    op.add_column('agentbasedconfig', sa.Column('human_equivalent_value', sa.Float(), nullable=True))
    op.add_column('outcomebasedconfig', sa.Column('human_equivalent_value', sa.Float(), nullable=True))
    op.add_column('workflowbasedconfig', sa.Column('human_equivalent_value', sa.Float(), nullable=True))
    op.add_column('workflowtype', sa.Column('human_equivalent_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflowtype', 'human_equivalent_value')
    op.drop_column('workflowbasedconfig', 'human_equivalent_value')
    op.drop_column('outcomebasedconfig', 'human_equivalent_value')
    op.drop_column('agentbasedconfig', 'human_equivalent_value')
    op.drop_column('activitybasedconfig', 'human_equivalent_value')
    # ### end Alembic commands ###
