"""Removed hybrid billing model

Revision ID: c3957c7e8da8
Revises: 1a6ee7631f5f
Create Date: 2025-07-06 20:20:53.030686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3957c7e8da8'
down_revision: Union[str, None] = '1a6ee7631f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hybridconfig_id'), table_name='hybridconfig')
    op.drop_table('hybridconfig')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hybridconfig',
    sa.Column('billing_model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['billing_model_id'], ['billingmodel.id'], name=op.f('hybridconfig_billing_model_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hybridconfig_pkey'))
    )
    op.create_index(op.f('ix_hybridconfig_id'), 'hybridconfig', ['id'], unique=False)
    # ### end Alembic commands ###
