"""add_description_column_to_integration_connectors

Revision ID: fe1e8e8782e3
Revises: 73279c084cb9
Create Date: 2025-06-01 11:06:19.595399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe1e8e8782e3'
down_revision: Union[str, None] = '73279c084cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_connectors', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('integration_connectors', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('integration_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('integration_streams', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_column('integration_streams', 'last_message_at')
    op.drop_column('integration_streams', 'message_count')
    op.alter_column('integration_webhooks', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # Convert ARRAY to JSON for event_types column
    op.execute("ALTER TABLE integration_webhooks ALTER COLUMN event_types TYPE JSON USING array_to_json(event_types)")
    op.drop_column('integration_webhooks', 'delivery_count')
    op.drop_column('integration_webhooks', 'failed_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_webhooks', sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('integration_webhooks', sa.Column('delivery_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('integration_webhooks', 'event_types',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=False)
    op.alter_column('integration_webhooks', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('integration_streams', sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('integration_streams', sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('integration_streams', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('integration_events', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('integration_connectors', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('integration_connectors', 'description')
    # ### end Alembic commands ###
